### ISSUE TITLE
Support struct comments from schema description

### ISSUE THREAD

**Issue by Antonboom** [kepkin/gorest#10]
Example:
```yaml
components:
  schemas:
  Transaction:
      type: object
      properties:
        id:
          type: string
          description: uuid usually
        datetime:
          type: string
          description: datetime in format ISO8601
```

```golang
type Transaction struct {
        // ID is uuid usually
	ID string `json:"id"`

        // Datetime is datetime in format ISO8601
 	Datetime `json:"id"`
}
```
