### ISSUE TITLE
Support boolean fields

### ISSUE THREAD

**Issue by Antonboom** [kepkin/gorest#11]
```yaml
        - name: download
          in: query
          schema:
            type: string
          description: download csv, example download=true
```

```golang
Download bool
```

https://swagger.io/docs/specification/data-models/data-types/#boolean
