### ISSUE TITLE
Invalid JSON tag for nested objects

### ISSUE THREAD

**Issue by Antonboom** [kepkin/gorest#16]
Input:
```yaml
    Settings:
      type: object
      properties:
        postAddress:
          description: Address object like dadata's
          type: object
          properties:
            value:
              description: Address as one string
              type: string
            data:
              type: object
              properties:
                postalCode:
                  type: string
                country:
                  type: string
```

Output:
```golang
type Settings struct {
	EdoOperator string                    `json:"edoOperator"`
	PostAddress WalletSettingsPostAddress `json:""`
	PostMethod  string                    `json:"postMethod"`
}

type SettingsPostAddress struct {
	Data  WalletSettingsPostAddressData `json:""`
	Value string                        `json:"value"`
}
```

We see `json:""` :(
