### ISSUE TITLE
Support no-object components

### ISSUE THREAD

**Issue by Antonboom** [kepkin/gorest#8]
Example:
```yaml
components:
  schemas:
    PolicyData:
      type: string
```
to
```golang
type PolicyData string
```
